In [45]:
import tensorflow as tf
import numpy as np


In [112]:
a = np.ones(shape=(2,3))

In [72]:
b = np.ones(shape=(3, 4))

In [109]:
di = np.array(range(0,10))

In [115]:
e = np.array([[1,2,3],[4,5,6]])

In [74]:
a_a = tf.Variable(a, name='a')
b_b = tf.Variable(b, name='b')

In [79]:
resout = tf.add_n([a,b])


In [99]:
c = tf.constant([1.1,2.1,0.52,4.9], dtype=tf.float32)
d = tf.constant([1.4,5.1,0.1,0.9], dtype=tf.float32)


In [95]:
x = tf.ceil(c)

In [105]:
sinc = tf.cos(c)

In [116]:
init = tf.global_variables_initializer()


In [107]:
with tf.Session() as sess:
    sess.run(init)
    print('*'*10)
    print('max:{}'.format(sess.run(tf.maximum(c,d))))
    print('*'*10)
    print('cos:{}'.format(sess.run(sinc)))
    print('*'*10)
    print(sess.run(x))
    print('*'*10)
    print(sess.run(a_a + b_b))
    print('*'*10)
    sess.run(resout)
    print(sess.run(resout))

**********
max:[1.4  5.1  0.52 4.9 ]
**********
cos:[ 0.45359612 -0.50484604  0.8678192   0.18651247]
**********
[2. 3. 1. 5.]
**********
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
**********
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [117]:

with tf.Session() as sess:
    print(sess.run(tf.diag(di)))
    print('*'*20)
    print(sess.run(tf.diag(a)))
    print('*'*20)
    print(sess.run(tf.diag(e)))

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]
********************
[[[[1. 0. 0.]
   [0. 0. 0.]]

  [[0. 1. 0.]
   [0. 0. 0.]]

  [[0. 0. 1.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [1. 0. 0.]]

  [[0. 0. 0.]
   [0. 1. 0.]]

  [[0. 0. 0.]
   [0. 0. 1.]]]]
********************
[[[[1 0 0]
   [0 0 0]]

  [[0 2 0]
   [0 0 0]]

  [[0 0 3]
   [0 0 0]]]


 [[[0 0 0]
   [4 0 0]]

  [[0 0 0]
   [0 5 0]]

  [[0 0 0]
   [0 0 6]]]]


In [154]:
e = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]],[[11,21,31],[41,51,61],[71,81,91]]])

In [155]:
e.shape
e

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]],

       [[11, 21, 31],
        [41, 51, 61],
        [71, 81, 91]]])

In [156]:
e_e = tf.Variable(e, name='e')

In [157]:
init = tf.global_variables_initializer()

In [158]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tf.transpose(e_e)))

[[[ 1 10 11]
  [ 4 40 41]
  [ 7 70 71]]

 [[ 2 20 21]
  [ 5 50 51]
  [ 8 80 81]]

 [[ 3 30 31]
  [ 6 60 61]
  [ 9 90 91]]]
